#!python3
import tkinter as tk

window = tk.Tk()
window.title('T-Town Veterinary Clinic Database')

dog = tk.PhotoImage(file='dog.png')
dogplace = tk.Label(window, image=dog, bg='#FFFFFF')
label1 = tk.Label(window,text='Client Database')
space1 = tk.Label(window)
button1 = tk.Button(window, text = 'Search by Name')
entery1 = tk.Entry(window, width=18, bg='#FFFFFF')
label2 = tk.Label(window,text='Name')
label3 = tk.Label(window,text='Type')
label4 = tk.Label(window,text='Breed')
label5 = tk.Label(window,text='Owner')
label6 = tk.Label(window,text='Birthdate')
entery2 = tk.Entry(window, width=15, bg='#FFFFFF')
entery3 = tk.Entry(window, width=15, bg='#FFFFFF')
entery4 = tk.Entry(window, width=15, bg='#FFFFFF')
entery5 = tk.Entry(window, width=15, bg='#FFFFFF')
entery6 = tk.Entry(window, width=15, bg='#FFFFFF')
button2 = tk.Button(window, text = '< Pervious', bg='#FFFFFF')
button3 = tk.Button(window, text = 'Save Entry', bg='#ACACAC', height=2)
button4 = tk.Button(window, text = 'Next >', bg='#FFFFFF')

dogplace.grid(row=1,column=1,rowspan=3)
button1.grid(row=1, column=4)
entery1.grid(row=1,column=5, padx=2)
label1.grid(row=2, column=3)
space1.grid(row=3, column=3)
label2.grid(row = 4, column=1)
label3.grid(row = 4, column=2)
label4.grid(row = 4, column=3)
label5.grid(row = 4, column=4)
label6.grid(row = 4, column=5)
entery2.grid(row = 5, column=1, padx=2)
entery3.grid(row = 5, column=2, padx=2)
entery4.grid(row = 5, column=3, padx=2)
entery5.grid(row = 5, column=4, padx=2)
entery6.grid(row = 5, column=5, padx=2)
button2.grid(row=6, column=1, sticky='W', pady=5)
button3.grid(row=6, column=3, pady=2)
button4.grid(row=6, column=5, sticky='E', pady=5)

window.mainloop()