#!python3
import tkinter as tk

window = tk.Tk()
window.title('T-Town Veterinary Clinic Database')

dog = tk.PhotoImage(file='dog.png')
dogplace = tk.Label(window, image=dog)
label1 = tk.Label(window,text='Client Database')
space1 = tk.Label(window)
button1 = tk.Button(window, text = 'Search by Name')
entery1 = tk.Entry(window)
label2 = tk.Label(window,text='Name')
label3 = tk.Label(window,text='Type')
label4 = tk.Label(window,text='Breed')
label5 = tk.Label(window,text='Owner')
label6 = tk.Label(window,text='Birthdate')
entery2 = tk.Entry(window)
entery3 = tk.Entry(window)
entery4 = tk.Entry(window)
entery5 = tk.Entry(window)
entery6 = tk.Entry(window)
button2 = tk.Button(window, text = '< Pervious')
button3 = tk.Button(window, text = 'Save Entry', bg='#ACACAC')
button4 = tk.Button(window, text = 'Next >')

dogplace.grid(row=1,column=1,rowspan=3)
button1.grid(row=1, column=4)
entery1.grid(row=1,column=5)
label1.grid(row=2, column=3)
space1.grid(row=3, column=3)
label2.grid(row = 4, column=1)
label3.grid(row = 4, column=2)
label4.grid(row = 4, column=3)
label5.grid(row = 4, column=4)
label6.grid(row = 4, column=5)
entery2.grid(row = 5, column=1)
entery3.grid(row = 5, column=2)
entery4.grid(row = 5, column=3)
entery5.grid(row = 5, column=4)
entery6.grid(row = 5, column=5)
button2.grid(row=6, column=1, sticky='W')
button3.grid(row=6, column=3)
button4.grid(row=6, column=5, sticky='E')

window.mainloop()